Process form 4
sec-edgar/sec-edgar pull request #254
Opened 2021-12-18 03:36 UTC by darrion

- [x] closes #253 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] added entry to docs/whatsnew latest version

2021-12-27 01:16 UTC, darrion commented
Resolved all linter warnings, executed tests, and confirmed branch is up to date with master.

2021-12-27 13:43 UTC, jackmoody11 requested changes
Only change needed is to change version added in doc string to 0.4.0.

2021-12-27 13:43 UTC, jackmoody11 commented on secedgar/parser.py
> +    .. versionadded:: 0.3.4
This should be 0.4.0

2021-12-28 00:21 UTC, darrion commented on secedgar/parser.py
> +    .. versionadded:: 0.3.4
Corrected it.

2021-12-28 13:52 UTC, jackmoody11 approved these changes

2021-12-28 13:53 UTC, merged

2021-12-28 13:54 UTC, jackmoody11 commented
Good work @darrion. Thanks for your help!